autd3: autd::_utils::Vector3 Class Reference
autd::_utils::Vector3 Class Reference
Simple three-dimensional vector class.
#include <vector3.hpp>
Public Member Functions
Vector3 () noexcept=default
Vector3 (double x, double y, double z) noexcept
Vector3 (const Vector3 &v) noexcept=default
Vector3 & operator= (const Vector3 &obj)=default
double x () const noexcept
double y () const noexcept
double z () const noexcept
double l2_norm_squared () const
double l2_norm () const
Vector3 normalized () const
double dot (const Vector3 &rhs) const
Vector3 cross (const Vector3 &rhs) const
double angle (const Vector3 &v) const
Vector3 & operator+= (const Vector3 &rhs)
Vector3 & operator-= (const Vector3 &rhs)
Vector3 & operator*= (const double &rhs)
Vector3 & operator/= (const double &rhs)
Static Public Member Functions
static Vector3 unit_x () noexcept
static Vector3 unit_y () noexcept
static Vector3 unit_z () noexcept
static Vector3 zero () noexcept
Friends
std::ostream & operator<< (std::ostream &, const Vector3 &)
bool operator== (const Vector3 &lhs, const Vector3 &rhs)
bool operator!= (const Vector3 &lhs, const Vector3 &rhs)
Vector3 operator+ (Vector3 lhs, const Vector3 &rhs)
Vector3 operator- (Vector3 lhs, const Vector3 &rhs)
Vector3 operator* (Vector3 lhs, const double &rhs)
Vector3 operator* (const double &lhs, Vector3 rhs)
Vector3 operator/ (Vector3 lhs, const double &rhs)
Detailed Description
Simple three-dimensional vector class.
Definition at line 27 of file vector3.hpp.
Constructor & Destructor Documentation
Vector3() [1/3]
autd::_utils::Vector3::Vector3 () default noexcept
Referenced by cross(), unit_x(), unit_y(), unit_z(), and zero().
Vector3() [2/3]
autd::_utils::Vector3::Vector3 (double x, double y, double z) inline noexcept
Definition at line 35 of file vector3.hpp.
Vector3() [3/3]
autd::_utils::Vector3::Vector3 (const Vector3 & v) default noexcept
Member Function Documentation
angle()
double autd::_utils::Vector3::angle (const Vector3 & v) const inline
Definition at line 55 of file vector3.hpp.
References dot(), and l2_norm().
cross()
Vector3 autd::_utils::Vector3::cross (const Vector3 & rhs) const inline
Definition at line 53 of file vector3.hpp.
References Vector3().
dot()
double autd::_utils::Vector3::dot (const Vector3 & rhs) const inline
Definition at line 52 of file vector3.hpp.
Referenced by angle().
l2_norm()
double autd::_utils::Vector3::l2_norm () const inline
Definition at line 43 of file vector3.hpp.
References l2_norm_squared().
Referenced by angle(), and normalized().
l2_norm_squared()
double autd::_utils::Vector3::l2_norm_squared () const inline
Definition at line 42 of file vector3.hpp.
Referenced by l2_norm().
normalized()
Vector3 autd::_utils::Vector3::normalized () const inline
Definition at line 50 of file vector3.hpp.
References l2_norm().
operator*=()
Vector3& autd::_utils::Vector3::operator*= (const double & rhs) inline
Definition at line 82 of file vector3.hpp.
operator+=()
Vector3& autd::_utils::Vector3::operator+= (const Vector3 & rhs) inline
Definition at line 70 of file vector3.hpp.
operator-=()
Vector3& autd::_utils::Vector3::operator-= (const Vector3 & rhs) inline
Definition at line 76 of file vector3.hpp.
operator/=()
Vector3& autd::_utils::Vector3::operator/= (const double & rhs) inline
Definition at line 88 of file vector3.hpp.
operator=()
Vector3& autd::_utils::Vector3::operator= (const Vector3 & obj) default
unit_x()
static Vector3 autd::_utils::Vector3::unit_x () inline static noexcept
Definition at line 45 of file vector3.hpp.
References Vector3().
unit_y()
static Vector3 autd::_utils::Vector3::unit_y () inline static noexcept
Definition at line 46 of file vector3.hpp.
References Vector3().
unit_z()
static Vector3 autd::_utils::Vector3::unit_z () inline static noexcept
Definition at line 47 of file vector3.hpp.
References Vector3().
x()
double autd::_utils::Vector3::x () const inline noexcept
Definition at line 39 of file vector3.hpp.
y()
double autd::_utils::Vector3::y () const inline noexcept
Definition at line 40 of file vector3.hpp.
z()
double autd::_utils::Vector3::z () const inline noexcept
Definition at line 41 of file vector3.hpp.
zero()
static Vector3 autd::_utils::Vector3::zero () inline static noexcept
Definition at line 48 of file vector3.hpp.
References Vector3().
Friends And Related Function Documentation
operator!=
bool operator!= (const Vector3 & lhs, const Vector3 & rhs) friend
Definition at line 123 of file vector3.hpp.
operator* [1/2]
Vector3 operator* (const double & lhs, Vector3 rhs) friend
Definition at line 107 of file vector3.hpp.
operator* [2/2]
Vector3 operator* (Vector3 lhs, const double & rhs) friend
Definition at line 103 of file vector3.hpp.
operator+
Vector3 operator+ (Vector3 lhs, const Vector3 & rhs) friend
Definition at line 95 of file vector3.hpp.
operator-
Vector3 operator- (Vector3 lhs, const Vector3 & rhs) friend
Definition at line 99 of file vector3.hpp.
operator/
Vector3 operator/ (Vector3 lhs, const double & rhs) friend
Definition at line 111 of file vector3.hpp.
operator<<
std::ostream& operator<< (std::ostream & os, const Vector3 & obj) friend
Definition at line 117 of file vector3.hpp.
operator==
bool operator== (const Vector3 & lhs, const Vector3 & rhs) friend
Definition at line 122 of file vector3.hpp.
The documentation for this class was generated from the following file:
include/vector3.hpp